//
// AccountDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class AccountDto: Decodable {


    public var id: String

    public var name: String?

    public var parentAccountId: String?

    public var adminId: String?

    public var address: String?

    public var description: String?

    public var isActive: Bool?

    public var isDeleted: Bool?

    public var photo: String?

    public var createdBy: String?

    public var createdAt: String?

    public var updatedBy: String?

    public var updatedAt: String?

    public var admin: UserDto?

    public var createdByNavigation: UserDto?

    weak var parentAccount: AccountDto?

    public var updatedByNavigation: UserDto?

    public var asset: [AssetDto]?

    public var inverseParentAccount: [AccountDto]?

    public var user: [UserDto]?
    
}
