//
// AccountStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct AccountStatus: Codable {


    public var _id: String

    public var isActive: Bool
    public init(_id: String, isActive: Bool) { 
        self._id = _id
        self.isActive = isActive
    }
    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case isActive
    }

}
