//
// AppointmentDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct AppointmentObject: Decodable {
    var success: Bool
    var data: AppointmentDto?
    var count: Int?
    var code: String?
    
}
public struct AppointmentListObject: Decodable {
    var success: Bool
    var data: [AppointmentDto]?
    var count: Int?
    var code: String?
    
}
public struct AppointmentDto: Decodable {


    public var id: String?

    public var dateTime: String?

    public var status: Int?

    public var description: String?

    public var assetId: String?

    public var brokerId: String?

    public var developerId: String?

    public var contactId: String?

    public var customerId: String?

    public var createdBy: String?

    public var createdAt: String?

    public var updatedBy: String?

    public var updatedAt: String?

    public var asset: AssetDto?

    public var broker : UserDtoMessageObject?

    public var contact: ContactDto?

   // weak var createdByNavigation: UserDto?

   // public var customer: UserDto?

    public var developer: UserDtoMessageObject?

  //  public var updatedByNavigation: UserDto?
   

}
