//
// AppointmentDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct AppointmentDto: Codable {


    public var _id: String

    public var dateTime: Date

    public var status: Int

    public var _description: String?

    public var assetId: String

    public var brokerId: String

    public var developerId: String

    public var contactId: String

    public var customerId: String?

    public var createdBy: String

    public var createdAt: Date

    public var updatedBy: String?

    public var updatedAt: Date?

    public var asset: AssetDto?

    weak var broker: UserDto?

    public var contact: ContactDto?

    weak var createdByNavigation: UserDto?

    public var customer: UserDto?

    public var developer: UserDto?

    public var updatedByNavigation: UserDto?
    public init(_id: String, dateTime: Date, status: Int, _description: String?, assetId: String, brokerId: String, developerId: String, contactId: String, customerId: String?, createdBy: String, createdAt: Date, updatedBy: String?, updatedAt: Date?, asset: AssetDto?, broker: UserDto?, contact: ContactDto?, createdByNavigation: UserDto?, customer: UserDto?, developer: UserDto?, updatedByNavigation: UserDto?) { 
        self._id = _id
        self.dateTime = dateTime
        self.status = status
        self._description = _description
        self.assetId = assetId
        self.brokerId = brokerId
        self.developerId = developerId
        self.contactId = contactId
        self.customerId = customerId
        self.createdBy = createdBy
        self.createdAt = createdAt
        self.updatedBy = updatedBy
        self.updatedAt = updatedAt
        self.asset = asset
        self.broker = broker
        self.contact = contact
        self.createdByNavigation = createdByNavigation
        self.customer = customer
        self.developer = developer
        self.updatedByNavigation = updatedByNavigation
    }
    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case dateTime
        case status
        case _description = "description"
        case assetId
        case brokerId
        case developerId
        case contactId
        case customerId
        case createdBy
        case createdAt
        case updatedBy
        case updatedAt
        case asset
        case broker
        case contact
        case createdByNavigation
        case customer
        case developer
        case updatedByNavigation
    }

}
