//
// AppointmentStatus.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct AppointmentStatus: Codable {


    public var _id: String

    public var status: Int
    public init(_id: String, status: Int) { 
        self._id = _id
        self.status = status
    }
    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case status
    }

}
