//
// AssetDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class AssetDto: Codable {


    public var _id: String

    public var title: String

    public var parentAssetId: String?

    public var ownerId: String

    public var accountId: String?

    public var assetTypeId: Int

    public var latitude: Double?

    public var longitude: Double?

    public var address: String?

    public var _description: String

    public var status: Int

    public var photo: String?

    public var profilePhoto: String?

    public var createdBy: String

    public var createdAt: Date

    public var updatedBy: String?

    public var updatedAt: Date?

    public var tages: [String]?

    public var account: AccountDto?

    public var assetType: AssetTypeDto?

    public var createdByNavigation: UserDto?

    public var owner: UserDto?

    weak var parentAsset: AssetDto?

    public var updatedByNavigation: UserDto?

    public var appointment: [AppointmentDto]?

    public var assetGallery: [AssetGalleryDto]?

    public var assetHashTag: [AssetHashTagDto]?

    public var inverseParentAsset: [AssetHashTagDto]?

    public var notification: [NotificationDto]?

    public var favoriteAsset: [FavoriteAssetDto]?
    public init(_id: String, title: String, parentAssetId: String?, ownerId: String, accountId: String?, assetTypeId: Int, latitude: Double?, longitude: Double?, address: String?, _description: String, status: Int, photo: String?, profilePhoto: String?, createdBy: String, createdAt: Date, updatedBy: String?, updatedAt: Date?, tages: [String]?, account: AccountDto?, assetType: AssetTypeDto?, createdByNavigation: UserDto?, owner: UserDto?, parentAsset: AssetDto?, updatedByNavigation: UserDto?, appointment: [AppointmentDto]?, assetGallery: [AssetGalleryDto]?, assetHashTag: [AssetHashTagDto]?, inverseParentAsset: [AssetHashTagDto]?, notification: [NotificationDto]?, favoriteAsset: [FavoriteAssetDto]?) {
        self._id = _id
        self.title = title
        self.parentAssetId = parentAssetId
        self.ownerId = ownerId
        self.accountId = accountId
        self.assetTypeId = assetTypeId
        self.latitude = latitude
        self.longitude = longitude
        self.address = address
        self._description = _description
        self.status = status
        self.photo = photo
        self.profilePhoto = profilePhoto
        self.createdBy = createdBy
        self.createdAt = createdAt
        self.updatedBy = updatedBy
        self.updatedAt = updatedAt
        self.tages = tages
        self.account = account
        self.assetType = assetType
        self.createdByNavigation = createdByNavigation
        self.owner = owner
        self.parentAsset = parentAsset
        self.updatedByNavigation = updatedByNavigation
        self.appointment = appointment
        self.assetGallery = assetGallery
        self.assetHashTag = assetHashTag
        self.inverseParentAsset = inverseParentAsset
        self.notification = notification
        self.favoriteAsset = favoriteAsset
    }
    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case title
        case parentAssetId
        case ownerId
        case accountId
        case assetTypeId
        case latitude
        case longitude
        case address
        case _description = "description"
        case status
        case photo
        case profilePhoto
        case createdBy
        case createdAt
        case updatedBy
        case updatedAt
        case tages
        case account
        case assetType
        case createdByNavigation
        case owner
        case parentAsset
        case updatedByNavigation
        case appointment
        case assetGallery
        case assetHashTag
        case inverseParentAsset
        case notification
        case favoriteAsset
    }

}
