//
// AssetTypeDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct AssetTypeObject: Decodable {
    var success: Bool
    var data: [AssetType]?
    var count: Int?
    var code: String?
    
}
public struct AssetType: Decodable {
    var id: Int
    var name: String?
    var isActive: Bool?
   
    
}
public struct AssetTypeDto: Decodable {


    public var id: Int

    public var code: String?

    public var text: String?

    public var isActive: Bool

    public var isDeleted: Bool

    public var asset: [AssetDto]?

}
