//
// AssetHashTagDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct AssetHashTagDto: Decodable {


    public var id: String?

    public var assetId: String?

    public var hashTagId: String?

    public var isActive: Bool?

    public var asset: AssetDto?

    public var hashTag: HashTagDto?

}
