//
// AssetDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct AssetObject: Decodable {
    var success: Bool
    var data: [AssetDto]?
    var count: Int?
    var code: String?
    
}
public class AssetDto: Decodable {
    public var id: String?

    public var title: String?

    public var parentAssetId: String?

    public var ownerId: String?

    public var accountId: String?

    public var assetTypeId: Int?

//    public var latitude: Double?
//
//    public var longitude: Double?

    public var address: String?

    public var description: String?

//    public var status: Int?
//
    public var photo: String?
//
   //public var profilePhoto: String?
//
//    public var createdBy: String?
//
//    public var createdAt: String?
//
//    public var updatedBy: String?
//
//    public var updatedAt: String?
//
    public var tages: [String]?
//
//    public var account: AccountDto?
//
//    public var assetType: AssetTypeDto?
//
//    public var createdByNavigation: UserDto?
//
    public var owner: UserDto?
//
//    weak var parentAsset: AssetDto?
//
//    public var updatedByNavigation: UserDto?
//
//    public var appointment: [AppointmentDto]?
//
//    public var assetGallery: [AssetGalleryDto]?
//
//    public var assetHashTag: [AssetHashTagDto]?
//
//    public var inverseParentAsset: [AssetHashTagDto]?
//
//    public var notification: [NotificationDto]?
//
//    public var favoriteAsset: [FavoriteAssetDto]?
   
}
