//
// AssetHashTagDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct AssetHashTagDto: Decodable {


    public var _id: Int

    public var assetId: String

    public var hashTagId: String

    public var isActive: Bool

    public var asset: AssetDto?

    public var hashTag: HashTagDto?
    public init(_id: Int, assetId: String, hashTagId: String, isActive: Bool, asset: AssetDto?, hashTag: HashTagDto?) { 
        self._id = _id
        self.assetId = assetId
        self.hashTagId = hashTagId
        self.isActive = isActive
        self.asset = asset
        self.hashTag = hashTag
    }
    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case assetId
        case hashTagId
        case isActive
        case asset
        case hashTag
    }

}
