//
// AssetGalleryDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct AssetGalleryDto: Decodable {


    public var id: String?

    public var name: String?

    public var path: String?

    public var description: String?

    public var isActive: Bool?

    public var assetId: String?

    public var itemTypeId: Int?

    public var createdBy: String?

    public var createdAt: Date?

    public var updatedBy: String?

    public var updatedAt: String?

    public var asset: AssetDto?

    weak var createdByNavigation: UserDto?

    public var itemType: GalleryItemTypeDto?

    public var updatedByNavigation: UserTypeDto?
   
}
