//
// ContactHashTagDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct ContactHashTagDto: Decodable {


    public var id: String?

    public var contactId: String?

    public var hashTagId: String?

    public var isActive: Bool?

    public var isDeleted: Bool?

    public var contact: ContactDto?

    public var hashTag: HashTagDto?
   
}
