//
// ContactDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct ContactDto: Decodable {


    public var id: String

    public var fullName: String?

    public var gender: Int?

    public var mobile: String?

    public var email: String?

    public var address: String?

    public var photo: String?

    public var brokerId: String?

    public var customerId: String?

    public var isDeleted: Bool?

    public var createdBy: String?

    public var createdAt: String?

    public var updatedBy: String?

    public var updatedAt: String?

    public var tages: [String]?

    public var broker: UserDto?

    public var createdByNavigation: UserDto?

    public var customer: UserDto?

    public var updatedByNavigation: UserDto?

    public var appointment: [AppointmentDto]?

    public var contactHashTag: [ContactHashTagDto]?

}
