//
// Fail.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct Fail: Codable {


    public var success: Bool

    public var data: BaseModel?

    public var count: Int64?

    public var code: String?
    public init(success: Bool, data: BaseModel?, count: Int64?, code: String?) {
        self.success = success
        self.data = data
        self.count = count
        self.code = code
    }

}
