//
// FavoriteAssetDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

public struct FavoriteAssetObject: Decodable {
    var success: Bool
    var data: FavoriteAssetDto?
    var count: Int?
    var code: String?
    
}

public struct FavoriteAssetDto: Decodable {


    public var id: String?

    public var assetId: String?

    public var userId: String?

    public var asset: AssetDto?

    public var user: UserDto?

}
