//
// FavoriteAssetDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct FavoriteAssetDto: Codable {


    public var _id: String

    public var assetId: String

    public var userId: String

    public var asset: AssetDto?

    public var user: UserDto?
    public init(_id: String, assetId: String, userId: String, asset: AssetDto?, user: UserDto?) { 
        self._id = _id
        self.assetId = assetId
        self.userId = userId
        self.asset = asset
        self.user = user
    }
    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case assetId
        case userId
        case asset
        case user
    }

}
