//
// Filter.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct Filter: Codable {


    public var key: String?

    public var value: String?
    public init(key: String?, value: String?) { 
        self.key = key
        self.value = value
    }

}
