//
// FollowerDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct FollowerDto: Decodable {


    public var id: String?

    public var followerId: String?

    public var followeeId: String?

    public var isDeleted: Bool?

    public var followee: UserDto?

    public var follower: UserDto?

    public var followerNavigation: UserDto?
   
}
