//
// GalleryItemTypeDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct GalleryItemTypeDto: Decodable {


    public var id: String?

    public var code: String?

    public var text: String?

    public var isActive: Bool

    public var isDeleted: Bool

    public var assetGallery: [AssetGalleryDto]?
   
}
