//
// GalleryItemTypeDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct GalleryItemTypeDto: Decodable {


    public var _id: Int

    public var code: String?

    public var text: String?

    public var isActive: Bool

    public var isDeleted: Bool

    public var assetGallery: [AssetGalleryDto]?
    public init(_id: Int, code: String?, text: String?, isActive: Bool, isDeleted: Bool, assetGallery: [AssetGalleryDto]?) { 
        self._id = _id
        self.code = code
        self.text = text
        self.isActive = isActive
        self.isDeleted = isDeleted
        self.assetGallery = assetGallery
    }
    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case code
        case text
        case isActive
        case isDeleted
        case assetGallery
    }

}
