//
// HashTagsDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct HashTagsDto: Decodable {


    public var id: String?

    public var parentHashTagId: String?

    public var childHashTagId: String?

    public var isDeleted: Bool?

    public var childHashTag: HashTagDto?

    public var parentHashTag: HashTagDto?

}
