//
// HashTagDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct HashTagDto: Decodable {


    public var id: String?

    public var text: String?

    public var isActive: Bool?

    public var isDeleted: Bool?

    public var assetHashTag: [AssetHashTagDto]?

    public var contactHashTag: [ContactHashTagDto]?

    public var hashTagsChildHashTag: [HashTagsDto]?

    public var hashTagsParentHashTag: [HashTagsDto]?

    public var userHashTag: [UserHashTagDto]?
}
