//
// MessageDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct MessageDto: Decodable {


    public var id: String?

    public var dateTime: String?

    public var body: String?

    public var toUserId: String?

    public var fromUserId: String?

    public var isDeleted: Bool?

    public var fromUser: UserDto?

    public var toUser: UserDto?
   
}
