//
// NotificationDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct NotificationDto: Decodable {


    public var id: String?

    public var dateTime: String?

    public var message: String?

    public var toUserId: String?

    public var fromUserId: String?

    public var assetId: String?

    public var isDeleted: Bool?

    weak var asset: AssetDto?

    weak var fromUser: UserDto?

    public var toUser: UserDto?
    
}
