//
// Success.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct Success: Decodable {


    public var success: Bool

    public var data: Object?

    public var count: Int?

    public var code: String?
    public init(success: Bool, data: Object?, count: Int?, code: String?) {
        self.success = success
        self.data = data
        self.count = count
        self.code = code
    }

}
