//
// UserTypeDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct UserTypeDto: Codable {


    public var _id: Int

    public var code: String?

    public var text: String?

    public var isActive: Bool

    public var user: [UserDto]?
    public init(_id: Int, code: String?, text: String?, isActive: Bool, user: [UserDto]?) { 
        self._id = _id
        self.code = code
        self.text = text
        self.isActive = isActive
        self.user = user
    }
    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case code
        case text
        case isActive
        case user
    }

}
