//
// UserLogin.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct UserLogin: Codable {


    public var email: String

    public var password: String
    public init(email: String, password: String) { 
        self.email = email
        self.password = password
    }

}
