//
// UserPassword.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct UserPassword: Codable {


    public var _id: String

    public var password: String
    public init(_id: String, password: String) { 
        self._id = _id
        self.password = password
    }
    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case password
    }

}
