//
// UserGroupUserDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct UserGroupUserDto: Decodable {


    public var _id: Int?

    public var userId: String?

    public var userGroupId: Int?

    public var isDeleted: Bool?

    weak var user: UserDto?

    weak var userGroup: UserGroupDto?
    public init(_id: Int?, userId: String?, userGroupId: Int?, isDeleted: Bool?, user: UserDto?, userGroup: UserGroupDto?) { 
        self._id = _id
        self.userId = userId
        self.userGroupId = userGroupId
        self.isDeleted = isDeleted
        self.user = user
        self.userGroup = userGroup
    }
    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case userId
        case userGroupId
        case isDeleted
        case user
        case userGroup
    }

}
