//
// UserTypeDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct UserTypeDto: Decodable {


    public var id: String?

    public var code: String?

    public var text: String?

    public var isActive: Bool?

    public var user: [UserDto]?
}
