//
// UserLogin.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct UserLogin: Codable {
    public var email: String?
    public var name: String?
    public var password: String?
    public var token: String?
    public var userProfile: UserProfileDto?

}
