//
// UserProfileDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct UserProfileDto: Codable {


    public var id: String

    public var fullName: String?

    public var gender: Int?

    public var address: String?

    public var photo: String?

    public var createdBy: String?

    public var createdAt: String?

    public var updatedBy: String?

    public var updatedAt: String?
    
}
