//
// UserHashTagDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct UserHashTagDto: Decodable {


    public var id: String?

    public var userId: String?

    public var hashTagId: String?

    public var isDeleted: Bool?

    public var hashTag: HashTagDto?

    public var user: UserDto?

}
