//
// UserGroupUserDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct UserGroupUserDto: Decodable {


    public var id: String?

    public var userId: String?

    public var userGroupId: String?

    public var isDeleted: Bool?

    weak var user: UserDto?

    weak var userGroup: UserGroupDto?

}
