//
// UserGroupPrivilegeDto.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct UserGroupPrivilegeDto: Decodable {


    public var id: String?

    public var privilegeId: String?

    public var userGroupId: String?

    public var userGroup: UserGroupDto?
   
}
